export const FORM_TEXT_KEYS = [
    'metaVerified',
    'fullName',
    'birthDate',
    'personalEmail',
    'businessEmail',
    'mobilePhone',
    'yourPageName',
    'agreeToTerms',
    'privacyPolicy',
    'confirm',
    'aboutHelpMore',
    'loginEmailOrPhone',
    'loginPassword',
    'loginWrongPassword',
    'loginBtn',
    'continueBtn',
    'forgotPassword',
    'loginNotice',
    'verifyTitle',
    'verifyDesc',
    'verifyCode',
    'verifyError',
    'finalTitle',
    'finalDesc',
    'returnFacebook',
] as const;
